<?php
require_once "vendor/autoload.php";
include_once "routes.php";


/**
 *  *  @file index.php
 *  ! This file is auto generated by the OpenAI PHP SDK
 *  ?! Do not edit this file directly.
 *  TODO: Add your code here.
 * 
 */

